// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(LeagueContext))]
    partial class LeagueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Speler", b =>
                {
                    b.Property<int>("SpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rugnummer")
                        .HasColumnType("int");

                    b.Property<int?>("TeamStamnummer")
                        .HasColumnType("int");

                    b.Property<int>("Waarde")
                        .HasColumnType("int");

                    b.HasKey("SpelerId");

                    b.HasIndex("TeamStamnummer");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("DataLayer.Team", b =>
                {
                    b.Property<int>("Stamnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stamnummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DataLayer.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NieuwTeamStamnummer")
                        .HasColumnType("int");

                    b.Property<int?>("OudTeamStamnummer")
                        .HasColumnType("int");

                    b.Property<double>("TransferPrijs")
                        .HasColumnType("float");

                    b.Property<int?>("TransferredSpelerSpelerId")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("NieuwTeamStamnummer");

                    b.HasIndex("OudTeamStamnummer");

                    b.HasIndex("TransferredSpelerSpelerId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("DataLayer.Speler", b =>
                {
                    b.HasOne("DataLayer.Team", null)
                        .WithMany("Spelers")
                        .HasForeignKey("TeamStamnummer");
                });

            modelBuilder.Entity("DataLayer.Transfer", b =>
                {
                    b.HasOne("DataLayer.Team", "NieuwTeam")
                        .WithMany()
                        .HasForeignKey("NieuwTeamStamnummer");

                    b.HasOne("DataLayer.Team", "OudTeam")
                        .WithMany()
                        .HasForeignKey("OudTeamStamnummer");

                    b.HasOne("DataLayer.Speler", "TransferredSpeler")
                        .WithMany()
                        .HasForeignKey("TransferredSpelerSpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
